### ISSUE TITLE
Web Share button doesn't display the icon

### ISSUE THREAD

**Issue by kytta** [kytta/shareon#75]
Seems there is an issue with the WebShare SVG.
https://picallow.com/wp-content/uploads/2023/07/2023-07-18_64b6c08182904_svg_issue.png

_Originally posted by @dourosdimitris in https://github.com/kytta/shareon/pull/67#issuecomment-1640572754_

**Comment by kytta** [comment]
@dourosdimitris I fixed the problem in code, but I accidentally uploaded the wrong code to NPM! This is now fixed in v2.2.3, with jsDelivr's caches purged 👌🏻

**Comment by dourosdimitris** [comment]
Great! 👍

Dimitrios Douros<https://douros.me/dimitrios>
________________________________
