### ISSUE TITLE
Twitter is Now X

### ISSUE THREAD

**Issue by vhsu** [kytta/shareon#86]
Twitter is now X and has a new logo  

https://www.theverge.com/2023/7/29/23812780/tweet-change-name-post-x

Tweet this is now post this

**Comment by kytta** [comment]
Finally, a situation where I can be a benevolent open-source dictator :)

The renaming of Twitter is dumb on so many levels. I will not accept any icon/colour changes and will close every issue and PR mentioning this.

The word "Tweet" that can be seen on the button is not part of Shareon and can be chosen freely by the site owner.

**Comment by kytta** [comment]
Btw, you can do it yourself, if you want to. Just update these lines:

https://github.com/kytta/shareon/blob/d5de42c40b06074efc5680391bb3fb096752005c/src/shareon.css#L179-L184

Change the colour to black, and change the icon to the one [from Simple Icons](https://simpleicons.org/?q=twitter)

cc: @sachin-arshna @kleinhev @MalcolmJohnston

**Comment by kleinhev** [comment]
Hi,

now how difficult is that for presumably many to change? Can you not add 
the new Twitter/X as a new option to the existing options? I do believe 
that X and the superapp ambitions of the self-declared free-speech 
absolutist will not last for a long time but right now it is just 
"standard" and cannot be ignored.




------ Original Message ------
From "Nikita Karamov" ***@***.***>
To "kytta/shareon" ***@***.***>
Cc "kleinhev" ***@***.***>; "Mention" 
***@***.***>
Date 12/03/2024 17:44:26
Subject Re: [kytta/shareon] Twitter is Now X (Issue #86)

**Comment by kleinhev** [comment]
... and others will choose to switch to a different product for that 
exact reason.



------ Original Message ------
From "Nikita Karamov" ***@***.***>
To "kytta/shareon" ***@***.***>
Cc "kleinhev" ***@***.***>; "Mention" 
***@***.***>
Date 12/03/2024 18:55:33
Subject Re: [kytta/shareon] Twitter is Now X (Issue #86)

**Comment by jfoclpf** [comment]
I really don't understand this issue @kytta 
It's your repo and you can do whatever you want, but the company changed name and you don't own the company ;)
If you want this repo to be updated you should update also its logo and name.
But of course, it's your call

**Comment by kytta** [comment]
> It's your repo and you can do whatever you want

Yes, that's my plan

> but the company changed name and you don't own the company ;)

But I own the repo :D

> If you want this repo to be updated you should update also its logo and name.

I don't really care. I was bored, so I made the buttons, but it's not a _product_ or something that I want to sell or market. I'll be fixing the breaking changes; and when twitter-dot-com ultimately stops working, I'll change the URL. But the logo is not a breaking change for me. IDK, I guess I'm weird 🤷🏻‍♂️

**Comment by jfoclpf** [comment]
You're free to do it, it's you repo ;)
It's just an extra work for me cause I have to tweak the repo with webpack
Anyway, thanks for the repo ;)

**Comment by kleinhev** [comment]
Yes, that is weird. Publishing something on Github exclusively for yourself and not for the community is weird.

**Comment by kytta** [comment]
> Publishing something on Github exclusively for yourself and not for the community is weird.

@kleinhev The code is literally open-source under a permissive licence. I've even given instructions on how to implement this. The fact that I do not rush to make changes when someone asks me to does not mean it's "exclusively for myself" and "not for the community".
